CREATE TABLE IF NOT EXISTS hackaton_client_data (
  id SERIAL PRIMARY KEY,
  client_name VARCHAR(255) DEFAULT NULL,
  client_middle_name VARCHAR(255) DEFAULT NULL,
  client_sirname VARCHAR(255) DEFAULT NULL,
  client_birthdate TIMESTAMP DEFAULT NULL,
  client_birthplace VARCHAR(255) DEFAULT NULL,
  client_mobile_phone VARCHAR(255) DEFAULT NULL,
  product VARCHAR(100) DEFAULT NULL,
  tariff VARCHAR(255) DEFAULT NULL,
  autosalon VARCHAR(255) DEFAULT NULL,
  client_education VARCHAR(255) DEFAULT NULL,
  client_passport_series VARCHAR(20) DEFAULT NULL,
  client_passport_number VARCHAR(20) DEFAULT NULL,
  client_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_passport_no_previous BOOLEAN DEFAULT NULL,
  client_zagran_passport_series VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_number VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_zagran_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_zagran_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_driver_license_series VARCHAR(255) DEFAULT NULL,
  client_driver_license_number VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_date TIMESTAMP DEFAULT NULL,
  client_driver_license_issue_place VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_code VARCHAR(255) DEFAULT NULL,
  credit_sum DECIMAL(12, 2) DEFAULT NULL,
  credit_term SMALLINT DEFAULT NULL,
  credit_initial DECIMAL(12, 2) DEFAULT NULL,
  credit_dog_issue_date TIMESTAMP DEFAULT NULL,
  client_family_status VARCHAR(255) DEFAULT NULL,
  client_children_dependents SMALLINT DEFAULT NULL,
  client_registration_address VARCHAR(255) DEFAULT NULL,
  client_registration_own_type VARCHAR(255) DEFAULT NULL,
  client_registration_date TIMESTAMP DEFAULT NULL,
  job_type VARCHAR(255) DEFAULT NULL,
  workplace_name VARCHAR(255) DEFAULT NULL,
  workplace_inn VARCHAR(255) DEFAULT NULL,
  workplace_client_position VARCHAR(255) DEFAULT NULL,
  workplace_address VARCHAR(255) DEFAULT NULL,
  workplace_phone VARCHAR(255) DEFAULT NULL,
  workplace_workdate TIMESTAMP DEFAULT NULL,
  workplace_work_experience SMALLINT DEFAULT NULL,
  workplace_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_type VARCHAR(255) DEFAULT NULL,
  car_brand VARCHAR(255) DEFAULT NULL,
  car_model VARCHAR(255) DEFAULT NULL,
  car_year VARCHAR(255) DEFAULT NULL,
  car_price DECIMAL(10, 2) DEFAULT NULL,
  car_dop_price DECIMAL(10, 2) DEFAULT NULL,
  car_type VARCHAR(255) DEFAULT NULL,
  car_condition VARCHAR(255) DEFAULT NULL,
  car_transmission VARCHAR(255) DEFAULT NULL,
  car_mileage VARCHAR(255) DEFAULT NULL,
  client_email VARCHAR(255) DEFAULT NULL,
  client_company VARCHAR(255) DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS sorted_d2 (
  id SERIAL PRIMARY KEY,
  client_name VARCHAR(255) DEFAULT NULL,
  client_middle_name VARCHAR(255) DEFAULT NULL,
  client_sirname VARCHAR(255) DEFAULT NULL,
  client_birthdate TIMESTAMP DEFAULT NULL,
  client_birthplace VARCHAR(255) DEFAULT NULL,
  client_mobile_phone VARCHAR(255) DEFAULT NULL,
  product VARCHAR(100) DEFAULT NULL,
  tariff VARCHAR(255) DEFAULT NULL,
  autosalon VARCHAR(255) DEFAULT NULL,
  client_education VARCHAR(255) DEFAULT NULL,
  client_passport_series VARCHAR(20) DEFAULT NULL,
  client_passport_number VARCHAR(20) DEFAULT NULL,
  client_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_passport_no_previous BOOLEAN DEFAULT NULL,
  client_zagran_passport_series VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_number VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_zagran_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_zagran_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_driver_license_series VARCHAR(255) DEFAULT NULL,
  client_driver_license_number VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_date TIMESTAMP DEFAULT NULL,
  client_driver_license_issue_place VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_code VARCHAR(255) DEFAULT NULL,
  credit_sum DECIMAL(12, 2) DEFAULT NULL,
  credit_term SMALLINT DEFAULT NULL,
  credit_initial DECIMAL(12, 2) DEFAULT NULL,
  credit_dog_issue_date TIMESTAMP DEFAULT NULL,
  client_family_status VARCHAR(255) DEFAULT NULL,
  client_children_dependents SMALLINT DEFAULT NULL,
  client_registration_address VARCHAR(255) DEFAULT NULL,
  client_registration_own_type VARCHAR(255) DEFAULT NULL,
  client_registration_date TIMESTAMP DEFAULT NULL,
  job_type VARCHAR(255) DEFAULT NULL,
  workplace_name VARCHAR(255) DEFAULT NULL,
  workplace_inn VARCHAR(255) DEFAULT NULL,
  workplace_client_position VARCHAR(255) DEFAULT NULL,
  workplace_address VARCHAR(255) DEFAULT NULL,
  workplace_phone VARCHAR(255) DEFAULT NULL,
  workplace_workdate TIMESTAMP DEFAULT NULL,
  workplace_work_experience SMALLINT DEFAULT NULL,
  workplace_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_type VARCHAR(255) DEFAULT NULL,
  car_brand VARCHAR(255) DEFAULT NULL,
  car_model VARCHAR(255) DEFAULT NULL,
  car_year VARCHAR(255) DEFAULT NULL,
  car_price DECIMAL(10, 2) DEFAULT NULL,
  car_dop_price DECIMAL(10, 2) DEFAULT NULL,
  car_type VARCHAR(255) DEFAULT NULL,
  car_condition VARCHAR(255) DEFAULT NULL,
  car_transmission VARCHAR(255) DEFAULT NULL,
  car_mileage VARCHAR(255) DEFAULT NULL,
  client_email VARCHAR(255) DEFAULT NULL,
  client_company VARCHAR(255) DEFAULT NULL,
  relevant_score INTEGER DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS sorted_leasing (
  id SERIAL PRIMARY KEY,
  client_name VARCHAR(255) DEFAULT NULL,
  client_middle_name VARCHAR(255) DEFAULT NULL,
  client_sirname VARCHAR(255) DEFAULT NULL,
  client_birthdate TIMESTAMP DEFAULT NULL,
  client_birthplace VARCHAR(255) DEFAULT NULL,
  client_mobile_phone VARCHAR(255) DEFAULT NULL,
  product VARCHAR(100) DEFAULT NULL,
  tariff VARCHAR(255) DEFAULT NULL,
  autosalon VARCHAR(255) DEFAULT NULL,
  client_education VARCHAR(255) DEFAULT NULL,
  client_passport_series VARCHAR(20) DEFAULT NULL,
  client_passport_number VARCHAR(20) DEFAULT NULL,
  client_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_passport_no_previous BOOLEAN DEFAULT NULL,
  client_zagran_passport_series VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_number VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_zagran_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_zagran_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_driver_license_series VARCHAR(255) DEFAULT NULL,
  client_driver_license_number VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_date TIMESTAMP DEFAULT NULL,
  client_driver_license_issue_place VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_code VARCHAR(255) DEFAULT NULL,
  credit_sum DECIMAL(12, 2) DEFAULT NULL,
  credit_term SMALLINT DEFAULT NULL,
  credit_initial DECIMAL(12, 2) DEFAULT NULL,
  credit_dog_issue_date TIMESTAMP DEFAULT NULL,
  client_family_status VARCHAR(255) DEFAULT NULL,
  client_children_dependents SMALLINT DEFAULT NULL,
  client_registration_address VARCHAR(255) DEFAULT NULL,
  client_registration_own_type VARCHAR(255) DEFAULT NULL,
  client_registration_date TIMESTAMP DEFAULT NULL,
  job_type VARCHAR(255) DEFAULT NULL,
  workplace_name VARCHAR(255) DEFAULT NULL,
  workplace_inn VARCHAR(255) DEFAULT NULL,
  workplace_client_position VARCHAR(255) DEFAULT NULL,
  workplace_address VARCHAR(255) DEFAULT NULL,
  workplace_phone VARCHAR(255) DEFAULT NULL,
  workplace_workdate TIMESTAMP DEFAULT NULL,
  workplace_work_experience SMALLINT DEFAULT NULL,
  workplace_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_type VARCHAR(255) DEFAULT NULL,
  car_brand VARCHAR(255) DEFAULT NULL,
  car_model VARCHAR(255) DEFAULT NULL,
  car_year VARCHAR(255) DEFAULT NULL,
  car_price DECIMAL(10, 2) DEFAULT NULL,
  car_dop_price DECIMAL(10, 2) DEFAULT NULL,
  car_type VARCHAR(255) DEFAULT NULL,
  car_condition VARCHAR(255) DEFAULT NULL,
  car_transmission VARCHAR(255) DEFAULT NULL,
  car_mileage VARCHAR(255) DEFAULT NULL,
  client_email VARCHAR(255) DEFAULT NULL,
  client_company VARCHAR(255) DEFAULT NULL,
  relevant_score INTEGER DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS sorted_autoexpress (
  id SERIAL PRIMARY KEY,
  client_name VARCHAR(255) DEFAULT NULL,
  client_middle_name VARCHAR(255) DEFAULT NULL,
  client_sirname VARCHAR(255) DEFAULT NULL,
  client_birthdate TIMESTAMP DEFAULT NULL,
  client_birthplace VARCHAR(255) DEFAULT NULL,
  client_mobile_phone VARCHAR(255) DEFAULT NULL,
  product VARCHAR(100) DEFAULT NULL,
  tariff VARCHAR(255) DEFAULT NULL,
  autosalon VARCHAR(255) DEFAULT NULL,
  client_education VARCHAR(255) DEFAULT NULL,
  client_passport_series VARCHAR(20) DEFAULT NULL,
  client_passport_number VARCHAR(20) DEFAULT NULL,
  client_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_passport_no_previous BOOLEAN DEFAULT NULL,
  client_zagran_passport_series VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_number VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_zagran_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_zagran_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_driver_license_series VARCHAR(255) DEFAULT NULL,
  client_driver_license_number VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_date TIMESTAMP DEFAULT NULL,
  client_driver_license_issue_place VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_code VARCHAR(255) DEFAULT NULL,
  credit_sum DECIMAL(12, 2) DEFAULT NULL,
  credit_term SMALLINT DEFAULT NULL,
  credit_initial DECIMAL(12, 2) DEFAULT NULL,
  credit_dog_issue_date TIMESTAMP DEFAULT NULL,
  client_family_status VARCHAR(255) DEFAULT NULL,
  client_children_dependents SMALLINT DEFAULT NULL,
  client_registration_address VARCHAR(255) DEFAULT NULL,
  client_registration_own_type VARCHAR(255) DEFAULT NULL,
  client_registration_date TIMESTAMP DEFAULT NULL,
  job_type VARCHAR(255) DEFAULT NULL,
  workplace_name VARCHAR(255) DEFAULT NULL,
  workplace_inn VARCHAR(255) DEFAULT NULL,
  workplace_client_position VARCHAR(255) DEFAULT NULL,
  workplace_address VARCHAR(255) DEFAULT NULL,
  workplace_phone VARCHAR(255) DEFAULT NULL,
  workplace_workdate TIMESTAMP DEFAULT NULL,
  workplace_work_experience SMALLINT DEFAULT NULL,
  workplace_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_type VARCHAR(255) DEFAULT NULL,
  car_brand VARCHAR(255) DEFAULT NULL,
  car_model VARCHAR(255) DEFAULT NULL,
  car_year VARCHAR(255) DEFAULT NULL,
  car_price DECIMAL(10, 2) DEFAULT NULL,
  car_dop_price DECIMAL(10, 2) DEFAULT NULL,
  car_type VARCHAR(255) DEFAULT NULL,
  car_condition VARCHAR(255) DEFAULT NULL,
  car_transmission VARCHAR(255) DEFAULT NULL,
  car_mileage VARCHAR(255) DEFAULT NULL,
  client_email VARCHAR(255) DEFAULT NULL,
  client_company VARCHAR(255) DEFAULT NULL,
  relevant_score INTEGER DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS sorted_hvoya (
  id SERIAL PRIMARY KEY,
  client_name VARCHAR(255) DEFAULT NULL,
  client_middle_name VARCHAR(255) DEFAULT NULL,
  client_sirname VARCHAR(255) DEFAULT NULL,
  client_birthdate TIMESTAMP DEFAULT NULL,
  client_birthplace VARCHAR(255) DEFAULT NULL,
  client_mobile_phone VARCHAR(255) DEFAULT NULL,
  product VARCHAR(100) DEFAULT NULL,
  tariff VARCHAR(255) DEFAULT NULL,
  autosalon VARCHAR(255) DEFAULT NULL,
  client_education VARCHAR(255) DEFAULT NULL,
  client_passport_series VARCHAR(20) DEFAULT NULL,
  client_passport_number VARCHAR(20) DEFAULT NULL,
  client_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_passport_no_previous BOOLEAN DEFAULT NULL,
  client_zagran_passport_series VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_number VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_zagran_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_zagran_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_driver_license_series VARCHAR(255) DEFAULT NULL,
  client_driver_license_number VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_date TIMESTAMP DEFAULT NULL,
  client_driver_license_issue_place VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_code VARCHAR(255) DEFAULT NULL,
  credit_sum DECIMAL(12, 2) DEFAULT NULL,
  credit_term SMALLINT DEFAULT NULL,
  credit_initial DECIMAL(12, 2) DEFAULT NULL,
  credit_dog_issue_date TIMESTAMP DEFAULT NULL,
  client_family_status VARCHAR(255) DEFAULT NULL,
  client_children_dependents SMALLINT DEFAULT NULL,
  client_registration_address VARCHAR(255) DEFAULT NULL,
  client_registration_own_type VARCHAR(255) DEFAULT NULL,
  client_registration_date TIMESTAMP DEFAULT NULL,
  job_type VARCHAR(255) DEFAULT NULL,
  workplace_name VARCHAR(255) DEFAULT NULL,
  workplace_inn VARCHAR(255) DEFAULT NULL,
  workplace_client_position VARCHAR(255) DEFAULT NULL,
  workplace_address VARCHAR(255) DEFAULT NULL,
  workplace_phone VARCHAR(255) DEFAULT NULL,
  workplace_workdate TIMESTAMP DEFAULT NULL,
  workplace_work_experience SMALLINT DEFAULT NULL,
  workplace_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_type VARCHAR(255) DEFAULT NULL,
  car_brand VARCHAR(255) DEFAULT NULL,
  car_model VARCHAR(255) DEFAULT NULL,
  car_year VARCHAR(255) DEFAULT NULL,
  car_price DECIMAL(10, 2) DEFAULT NULL,
  car_dop_price DECIMAL(10, 2) DEFAULT NULL,
  car_type VARCHAR(255) DEFAULT NULL,
  car_condition VARCHAR(255) DEFAULT NULL,
  car_transmission VARCHAR(255) DEFAULT NULL,
  car_mileage VARCHAR(255) DEFAULT NULL,
  client_email VARCHAR(255) DEFAULT NULL,
  client_company VARCHAR(255) DEFAULT NULL,
  relevant_score INTEGER DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS sorted_expocar (
  id SERIAL PRIMARY KEY,
  client_name VARCHAR(255) DEFAULT NULL,
  client_middle_name VARCHAR(255) DEFAULT NULL,
  client_sirname VARCHAR(255) DEFAULT NULL,
  client_birthdate TIMESTAMP DEFAULT NULL,
  client_birthplace VARCHAR(255) DEFAULT NULL,
  client_mobile_phone VARCHAR(255) DEFAULT NULL,
  product VARCHAR(100) DEFAULT NULL,
  tariff VARCHAR(255) DEFAULT NULL,
  autosalon VARCHAR(255) DEFAULT NULL,
  client_education VARCHAR(255) DEFAULT NULL,
  client_passport_series VARCHAR(20) DEFAULT NULL,
  client_passport_number VARCHAR(20) DEFAULT NULL,
  client_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_passport_no_previous BOOLEAN DEFAULT NULL,
  client_zagran_passport_series VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_number VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_zagran_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_zagran_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_driver_license_series VARCHAR(255) DEFAULT NULL,
  client_driver_license_number VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_date TIMESTAMP DEFAULT NULL,
  client_driver_license_issue_place VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_code VARCHAR(255) DEFAULT NULL,
  credit_sum DECIMAL(12, 2) DEFAULT NULL,
  credit_term SMALLINT DEFAULT NULL,
  credit_initial DECIMAL(12, 2) DEFAULT NULL,
  credit_dog_issue_date TIMESTAMP DEFAULT NULL,
  client_family_status VARCHAR(255) DEFAULT NULL,
  client_children_dependents SMALLINT DEFAULT NULL,
  client_registration_address VARCHAR(255) DEFAULT NULL,
  client_registration_own_type VARCHAR(255) DEFAULT NULL,
  client_registration_date TIMESTAMP DEFAULT NULL,
  job_type VARCHAR(255) DEFAULT NULL,
  workplace_name VARCHAR(255) DEFAULT NULL,
  workplace_inn VARCHAR(255) DEFAULT NULL,
  workplace_client_position VARCHAR(255) DEFAULT NULL,
  workplace_address VARCHAR(255) DEFAULT NULL,
  workplace_phone VARCHAR(255) DEFAULT NULL,
  workplace_workdate TIMESTAMP DEFAULT NULL,
  workplace_work_experience SMALLINT DEFAULT NULL,
  workplace_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_type VARCHAR(255) DEFAULT NULL,
  car_brand VARCHAR(255) DEFAULT NULL,
  car_model VARCHAR(255) DEFAULT NULL,
  car_year VARCHAR(255) DEFAULT NULL,
  car_price DECIMAL(10, 2) DEFAULT NULL,
  car_dop_price DECIMAL(10, 2) DEFAULT NULL,
  car_type VARCHAR(255) DEFAULT NULL,
  car_condition VARCHAR(255) DEFAULT NULL,
  car_transmission VARCHAR(255) DEFAULT NULL,
  car_mileage VARCHAR(255) DEFAULT NULL,
  client_email VARCHAR(255) DEFAULT NULL,
  client_company VARCHAR(255) DEFAULT NULL,
  relevant_score INTEGER DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS sorted_expobank (
  id SERIAL PRIMARY KEY,
  client_name VARCHAR(255) DEFAULT NULL,
  client_middle_name VARCHAR(255) DEFAULT NULL,
  client_sirname VARCHAR(255) DEFAULT NULL,
  client_birthdate TIMESTAMP DEFAULT NULL,
  client_birthplace VARCHAR(255) DEFAULT NULL,
  client_mobile_phone VARCHAR(255) DEFAULT NULL,
  product VARCHAR(100) DEFAULT NULL,
  tariff VARCHAR(255) DEFAULT NULL,
  autosalon VARCHAR(255) DEFAULT NULL,
  client_education VARCHAR(255) DEFAULT NULL,
  client_passport_series VARCHAR(20) DEFAULT NULL,
  client_passport_number VARCHAR(20) DEFAULT NULL,
  client_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_passport_no_previous BOOLEAN DEFAULT NULL,
  client_zagran_passport_series VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_number VARCHAR(20) DEFAULT NULL,
  client_zagran_passport_issue_date TIMESTAMP DEFAULT NULL,
  client_zagran_passport_issue_place VARCHAR(200) DEFAULT NULL,
  client_zagran_passport_issue_code VARCHAR(50) DEFAULT NULL,
  client_driver_license_series VARCHAR(255) DEFAULT NULL,
  client_driver_license_number VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_date TIMESTAMP DEFAULT NULL,
  client_driver_license_issue_place VARCHAR(255) DEFAULT NULL,
  client_driver_license_issue_code VARCHAR(255) DEFAULT NULL,
  credit_sum DECIMAL(12, 2) DEFAULT NULL,
  credit_term SMALLINT DEFAULT NULL,
  credit_initial DECIMAL(12, 2) DEFAULT NULL,
  credit_dog_issue_date TIMESTAMP DEFAULT NULL,
  client_family_status VARCHAR(255) DEFAULT NULL,
  client_children_dependents SMALLINT DEFAULT NULL,
  client_registration_address VARCHAR(255) DEFAULT NULL,
  client_registration_own_type VARCHAR(255) DEFAULT NULL,
  client_registration_date TIMESTAMP DEFAULT NULL,
  job_type VARCHAR(255) DEFAULT NULL,
  workplace_name VARCHAR(255) DEFAULT NULL,
  workplace_inn VARCHAR(255) DEFAULT NULL,
  workplace_client_position VARCHAR(255) DEFAULT NULL,
  workplace_address VARCHAR(255) DEFAULT NULL,
  workplace_phone VARCHAR(255) DEFAULT NULL,
  workplace_workdate TIMESTAMP DEFAULT NULL,
  workplace_work_experience SMALLINT DEFAULT NULL,
  workplace_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_amount DECIMAL(12, 2) DEFAULT NULL,
  workplace_additional_income_type VARCHAR(255) DEFAULT NULL,
  car_brand VARCHAR(255) DEFAULT NULL,
  car_model VARCHAR(255) DEFAULT NULL,
  car_year VARCHAR(255) DEFAULT NULL,
  car_price DECIMAL(10, 2) DEFAULT NULL,
  car_dop_price DECIMAL(10, 2) DEFAULT NULL,
  car_type VARCHAR(255) DEFAULT NULL,
  car_condition VARCHAR(255) DEFAULT NULL,
  car_transmission VARCHAR(255) DEFAULT NULL,
  car_mileage VARCHAR(255) DEFAULT NULL,
  client_email VARCHAR(255) DEFAULT NULL,
  client_company VARCHAR(255) DEFAULT NULL,
  relevant_score INTEGER DEFAULT NULL
);
