version: "3.7"
services:
  postgres:
    container_name: fastapi-postgres-container
    image: postgres:16.2
    restart: unless-stopped
    env_file:
     - .env
    environment:
        TZ: 'GMT+3'
        PGTZ: 'GMT+3'
    volumes:
      - postgres-data:/var/lib/postgresql/fastapi-db
      - ./postgres-init-db:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


volumes:
  postgres-data:
  